cache:
  key: '123'
  paths:
    - node_modules/
before_script:
  - node -v
  - npm -v
  - npm config set registry " https://registry.npm.taobao.org"
  - npm install
  - npm run build
  - npm run eslint
build_master:
  only:
    - master
  script:
    - npm run pm2:reload
    - echo 'build success123'

build_not_master:
  except:
    - master
  script:
    - echo 'build success'
