before_script:
  - node -v
  - npm -v
  - npm config set registry " https://registry.npm.taobao.org"
  - npm install 
  - npm run eslint
  - npm run build:all
build_master:
  only:
    - master
  script:
    - echo 'build success123'

build_not_master:
  except:
    - master
  script:
    - echo 'build success'
